### ISSUE TITLE
Function parameter/arguments

### ISSUE THREAD

**Issue by ryvexc** [Ttimofeyka/Rave#18]
how about parameter and arguments? seems like your method doesnt have any parameter or arguments

**Comment by Ttimofeyka** [comment]
Hello.

If you mean arguments and parameters, then working with them is indicated in the documentation (the reference folder), but I can show a small example:

`
(inline) void a {} // The code of this function (if possible) will be substituted instead of generating this function and calling it.

struct A {
    int a;

    A this => this; // Standard constructor.
    // If you need to return a pointer to memory in the heap, you can simply add the '*' character to the constructor type - the compiler will do everything for you.
    // Example: A* this => this;

    (inline, linkname: "firstMethod_of_A") void firstMethod {} // Method inside structure A.
    // Methods declared inside the structure cannot have the ctargs parameter due to compiler time constraints.
}

(method) void secondMethod(A* this) {
    // You can also declare methods outside of structures.
}
`
